name: test3

on:

  push:
    branches: [ "branch1" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Run multi-line script
        run: |
          echo what is the directory ?
          ls -a 
          echo To installing maven
          sudo apt update
          echo checking java version
          java -version
          sudo apt-get install -y maven 
          echo checking maven version
          maven -version
          echo task complete!!
