name: test4

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "branch1" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Run multi-line script
        run: |
          echo what is the directory ?
          ls -a 
          echo To installing maven
          sudo apt update
          echo checking java version
          java -version
          sudo apt-get install -y maven 
          echo checking maven version
          mvn -version
          echo task complete !!
      
  build-on-ubuntu:
      runs-on: ubuntu-latest
     
      steps:
      -  name: Run to know workspace location on this created vm
         run: |
           echo workspace is 
           echo $RUNNER_WORKSPACE 
           echo who is running this ?
           whoami
           echo disk available
           df 
           echo show available env varibles
           env

  build-on-windows: 
      runs-on: windows-latest

      steps:
      -  name: run windows Commands
         run: |
           echo Hii Welcome to Windows
           echo get-location Commands
           Get-Location          
